go:
  - "1.10.x"
  - "1.11.x"
  - "1.12.x"
  - "1.13.x"
  - "1.14.x"
  - "1.15.x"
  - tip

language: go

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

script:
  - make unit-test
  - make test


after_script:
  # Send code coverage report to coveralls.io
  - goveralls -service=travis-ci -coverprofile=combined.coverprofile

sudo: false
