before_install:
  - travis_retry go get -u golang.org/x/tools/cmd/cover
  - travis_retry go get -u golang.org/x/lint/golint

go:
  - "1.13.x"
  - "1.14.x"
  - "1.15.x"
  - "1.16.x"  

language: go

script:
  - make lint
  - make unit-test
  - make test


after_script:
  # Send code coverage report to coveralls.io
  - goveralls -service=travis-ci -coverprofile=combined.coverprofile

sudo: false
